name = "vortech-website"
type = "javascript"
main = "src/index.ts"
compatibility_date = "2026-04-15"

[build]
command = "npm run build"
output_directory = ".next"

[env.production]
name = "vortech-website-production"
